### ISSUE TITLE
How can i visualise the map from ov_maplab

### ISSUE THREAD

**Issue by Aishkrish18** [rpng/ov_maplab#13]
Hello,
As per the instructions i tried to follow them and perform mapping with euroc mav dataset. On performing that, i got the following errors
1. roslaunch ov_maplab serial.launch config:=euroc_mav dataset:=V1_02_medium
On launching this, it works for the entire dataset and in theend this is the error i get. 
![Screenshot from 2023-09-13 11-34-51](https://github.com/rpng/ov_maplab/assets/47241581/fa06ca90-5324-4b98-8c6f-3700124ed115)
2. On logging into the console, after loading the map i get these errors : 
![Screenshot from 2023-09-13 11-35-36](https://github.com/rpng/ov_maplab/assets/47241581/37dfb574-ed51-4d5c-a18c-9184d1e4a439)
although it foundthe map , the msg says no map found /only one map available. 
3. on typing visualize or  v --vis_color_by_mission, i cant visualize the map, it does nothing. How can i load / visualise the map. 
How can i load the map on rviz to see the map? 

Thanks for your reply.

**Comment by Aishkrish18** [comment]
Hello, quick update on this issue.
 Upon reading the maplab framework , i understood that after loading the map through the maplab console, I was able to visualise it on rviz where the topics where displayed. This worked finally for the sample dataset V0_1 medium dataset. 

On using my own dataset , on running the ov_maplab serial. launch i get this error : 
![Screenshot from 2023-09-13 17-02-38](https://github.com/rpng/ov_maplab/assets/47241581/b5f4ec10-fe2b-4400-a85d-b98471da2f47)

My dataset that i recorded looks like this : 
![Screenshot from 2023-09-13 17-10-22](https://github.com/rpng/ov_maplab/assets/47241581/2051322a-19a7-4b5a-9a72-8cc4cea52158)

I also want to know how i can use the map that is saved in maplab to directly load it on rviz with the points.

**Comment by goldbattle** [comment]
The vimap folder should be populated with data. Then you can interact with it directly using all the maplab tools. You will need to load the map into the maplab console and then visualize it. I do have a rviz config that should allow you to see the maplab topics here: https://github.com/rpng/ov_maplab/tree/master/launch

Are you running the the maplab commit specified in the readme of this repo?
It looks like there is some issue with the first vertex, but it should have been fixed in this commit: 
https://github.com/rpng/ov_maplab/commit/6182b4dcab9ca44c27c8163f0479a703aee82c9a#diff-935f27651aeecbaedcd938a857fda6c65dd73f1641b220e1130499c19606338eR258-R261

I recommend reading the maplab wiki for how to use maplab. To see the map, you will need to use maplab itself directly (thus nothing in ov_maplab will do this for you).

**Comment by goldbattle** [comment]
I would make sure you can run it through `ov_msckf` serial first with your config. From the printed "TIME:" it looks like there is some topic parsing issue likely. If you post your bag, configs and launch this would allow me and others to debug.
